[package]
name = "my_package"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "my_package"
path = "src/main.rs"

[lib]
name = "my_package"
path = "src/lib.rs"