[default.databases.main_connection]
url='postgresql://localhost:5432/rust_learning'

[debug.databases.main_connection]
url='postgresql://localhost:5432/rust_learning'

[release.databases.main_connection]
url='postgresql://localhost:5432/rust_learning'